# Site settings
author: Dominique Skaf
title: My Flatiron Projects
header-img: img/home-bg.png
email: doskaf@yahoo.com
copyright_name: Dominique Skaf
description: > # this means to ignore newlines until "baseurl:"
  Processes, reflections, and more!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  doskaf

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
